
var people = new JustGage({
    id: "people",
    value: 5,
    min: 0,
    max: 10,
    label: "Target 6 - 8",
    labelFontColor: "#000000",
    title: "People-Orientation",
    titleFontColor: "#000000",
    shadowOpacity: 0.5,
    shadowSize: 7,
    shadowVerticalOffset: 0,
    levelColors: ["#FB8301", "#FB8301", "#FB8301"],
    gaugeWidthScale: .45,
});
var summaryPeople = new JustGage({
    id: "summary__people",
    value: 5,
    min: 0,
    max: 10,
    label: "Target 6 - 8",
    labelFontColor: "#000000",
    shadowOpacity: 0.5,
    shadowSize: 7,
    shadowVerticalOffset: 0,
    levelColors: ["#FB8301", "#FB8301", "#FB8301"],
    gaugeWidthScale: .45,

});
var stress = new JustGage({
    id: "stress",
    value: 9,
    min: 0,
    max: 10,
    label: "Target 6 - 8",
    labelFontColor: "#000000",
    title: "Stress Tolerance",
    titleFontColor: "#000000",
    shadowOpacity: 0.5,
    shadowSize: 7,
    shadowVerticalOffset: 0,
    levelColors: ["#FB8301", "#FB8301", "#FB8301"],
    gaugeWidthScale: .45,
});
var summaryStress = new JustGage({
    id: "summary__stress",
    value: 9,
    min: 0,
    max: 10,
    label: "Target 6 - 8",
    labelFontColor: "#000000",
    shadowOpacity: .5,
    shadowSize: 7,
    shadowVerticalOffset: 0,
    levelColors: ["#FB8301", "#FB8301", "#FB8301"],
    gaugeWidthScale: .45,
});
var practicality = new JustGage({
    id: "practicality",
    value: 8,
    min: 0,
    max: 10,
    label: "Target 6 - 8",
    labelFontColor: "#000000",
    title: "Practicality",
    titleFontColor: "#000000",
    shadowOpacity: 0.5,
    shadowSize: 7,
    shadowVerticalOffset: 0,
    levelColors: ["#FB8301", "#FB8301", "#FB8301"],
    gaugeWidthScale: .45,
});
var summaryPracticality = new JustGage({
    id: "summary__practicality",
    value: 7,
    min: 0,
    max: 10,
    label: "Target 6 - 8",
    labelFontColor: "#000000",
    shadowOpacity: 0.5,
    shadowSize: 7,
    shadowVerticalOffset: 0,
    levelColors: ["#FB8301", "#FB8301", "#FB8301"],
    gaugeWidthScale: .45,
});
var drive = new JustGage({
    id: "drive",
    value: 6,
    min: 0,
    max: 10,
    label: "Target 6 - 8",
    labelFontColor: "#000000",
    title: "Drive / Influence",
    titleFontColor: "#000000",
    shadowOpacity: 0.5,
    shadowSize: 7,
    shadowVerticalOffset: 0,
    levelColors: ["#FB8301", "#FB8301", "#FB8301"],
    gaugeWidthScale: .45,
});
var summaryDrive = new JustGage({
    id: "summary__drive",
    value: 6,
    min: 0,
    max: 10,
    label: "Target 6 - 8",
    labelFontColor: "#000000",
    shadowOpacity: 0.5,
    shadowSize: 7,
    shadowVerticalOffset: 0,
    levelColors: ["#FB8301", "#FB8301", "#FB8301"],
    gaugeWidthScale: .45,
});
var conscientiousness = new JustGage({
    id: "conscientiousness",
    value: 9,
    min: 0,
    max: 10,
    label: "Target 6 - 8",
    labelFontColor: "#000000",
    title: "Conscientiousness",
    titleFontColor: "#000000",
    shadowOpacity: 0.5,
    shadowSize: 7,
    shadowVerticalOffset: 0,
    levelColors: ["#FB8301", "#FB8301", "#FB8301"],
    gaugeWidthScale: .45,
});
var summaryConscientiousness = new JustGage({
    id: "summary__conscientiousness",
    value: 9,
    min: 0,
    max: 10,
    label: "Target 6 - 8",
    labelFontColor: "#000000",
    shadowOpacity: 0.5,
    shadowSize: 7,
    shadowVerticalOffset: 0,
    levelColors: ["#FB8301", "#FB8301", "#FB8301"],
    gaugeWidthScale: .45,
});