
            var drive = new JustGage({
                id: "intellectual",
                value: 72,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                title: "Intellectual",
                titleFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            var summaryIntellectual = new JustGage({
                id: "summary__intellectual",
                value: 72,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            var drive = new JustGage({
                id: "drive",
                value: 72,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                title: "Drive / Influence",
                titleFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            var summaryDrive = new JustGage({
                id: "summary__drive",
                value: 72,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            var stress = new JustGage({
                id: "stress",
                value: 82,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                title: "Stress Tolerance",
                titleFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            var summaryStress = new JustGage({
                id: "summary__stress",
                value: 82,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                shadowOpacity: .5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            var people = new JustGage({
                id: "people",
                value: 78,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                title: "People Orientation",
                titleFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            var summaryPeople = new JustGage({
                id: "summary__people",
                value: 78,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,

            });
            var practicality = new JustGage({
                id: "practicality",
                value: 98,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                title: "Practicality",
                titleFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            var summaryPracticality = new JustGage({
                id: "summary__practicality",
                value: 98,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            var conscientiousness = new JustGage({
                id: "conscientiousness",
                value: 74,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                title: "Conscientiousness",
                titleFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            var summaryConscientiousness = new JustGage({
                id: "summary__conscientiousness",
                value: 74,
                min: 0,
                max: 100,
                label: "Target 60 - 80",
                labelFontColor: "#000000",
                shadowOpacity: 0.5,
                shadowSize: 7,
                shadowVerticalOffset: 0,
                levelColors: ["#FB8301", "#FB8301", "#FB8301"],
                gaugeWidthScale: .45,
            });
            // All scales are 0 to 100.

            // var f = new JustGage({
            //     id: "g12",
            //     value: getRandomInt(0, 100),
            //     min: 0,
            //     max: 100,
            //     title: "Custom Shadow",
            //     label: "",
            //     shadowOpacity: 0.5,
            //     shadowSize: 0,
            //     shadowVerticalOffset: 10
            // });
        